/**
 * One-shot Codex child lifecycle: spawn the real app-server through the
 * subprocess seam, publish only after initialization and ephemeral thread
 * creation, flatten post-publication failures, and dispose to whole-tree
 * quiescence.
 *
 * @module @deepseek-ai/dsh-subagent-codex/run
 */

import { randomUUID } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, resolve } from 'node:path'
import type { ContentBlock } from '@deepseek-ai/dsh-llm'
import { SessionId } from '@deepseek-ai/dsh-session'
import {
  settleRunResult,
  subprocessRunHandle,
  type SubagentResult,
  type SubagentRun,
  type SubagentStartRequest,
  type SubagentStopReason,
} from '@deepseek-ai/dsh-subagent'
import type {
  SubprocessHandle,
  SubprocessOutcome,
  SubprocessSpawnSpec,
} from '@deepseek-ai/dsh-subprocess'
import {
  CodexAppServerWire,
  type CodexWireFailureFacts,
} from './wire.ts'

/** Default POSIX grace between subprocess termination tiers. */
export const DEFAULT_DISPOSE_GRACE_MS = 3_000

interface CodexPackageManifest {
  readonly bin: {
    readonly codex: string
  }
}

const codexPackageJsonPath = createRequire(import.meta.url).resolve('@openai/codex/package.json')
const codexPackageManifest = JSON.parse(
  readFileSync(codexPackageJsonPath, 'utf8'),
) as CodexPackageManifest

/** Absolute package-local JavaScript wrapper selected by the package manifest. */
const CODEX_PACKAGE_BIN = resolve(
  dirname(codexPackageJsonPath),
  codexPackageManifest.bin.codex,
)

/** Profile-selectable non-interactive Codex permission mode. */
export type CodexPermissionMode =
  | 'never'
  | 'approve-for-me'
  | 'dangerously-bypass-approvals-and-sandbox'

/** Native non-interactive Codex modes mapped to official `thread/start` fields. */
export const CODEX_PERMISSION_MODES = [
  'never',
  'approve-for-me',
  'dangerously-bypass-approvals-and-sandbox',
] as const satisfies readonly CodexPermissionMode[]

/** Safe default for unattended Codex runs. */
export const DEFAULT_CODEX_PERMISSION_MODE: CodexPermissionMode = 'never'

/** The `SandboxMode` values a per-run route may select. */
export const CODEX_ROUTED_SANDBOXES = ['read-only', 'workspace-write'] as const

/** Filesystem authority a per-run route may select; never `danger-full-access`. */
export type CodexRoutedSandbox = typeof CODEX_ROUTED_SANDBOXES[number]

/**
 * Per-run routing overrides.
 *
 * Both field names are taken from the app-server JSON schema generated by the
 * pinned `@openai/codex` package (`app-server generate-json-schema`), not from
 * documentation: `TurnStartParams.model` is `string | null`,
 * `TurnStartParams.effort` is `ReasoningEffort | null`, and
 * `ThreadStartParams.sandbox` is a `SandboxMode`. `effort` exists only on
 * `turn/start` — `ThreadStartParams` has no effort field at all — which is why
 * the model travels beside it on the turn rather than on the thread. Sandbox
 * has no `turn/start` counterpart of the same shape, so it travels on the
 * thread, which is also where it belongs: filesystem authority is a property
 * of the whole run, not of one turn within it.
 *
 * An absent field means "do not override": the run then uses whatever the
 * user's own Codex configuration already selects. Nothing here reads or writes
 * `CODEX_HOME` or any other global Codex default.
 */
export interface CodexRouting {
  /** Model id for this turn, or absent to keep the configured default. */
  readonly model?: string
  /**
   * Sandbox mode emitted on `thread/start`, or absent to keep whatever the
   * selected permission mode already implies.
   *
   * `ThreadStartParams.sandbox` is a `SandboxMode`, whose schema enum is
   * `read-only | workspace-write | danger-full-access`. Only the first two are
   * routable: `danger-full-access` stays reachable exclusively through the
   * deployment-owned `dangerously-bypass-approvals-and-sandbox` permission
   * mode, so a per-run route can tighten filesystem authority but can never
   * hand a run full access that the deployment did not configure.
   */
  readonly sandbox?: CodexRoutedSandbox
  /**
   * Reasoning effort for this turn, or absent to keep the model's default.
   *
   * The schema types `ReasoningEffort` as a non-empty string described as "a
   * non-empty reasoning effort value advertised by the model" — deliberately
   * not a closed enum, because the advertised set is per-model and is read
   * from `Model.supportedReasoningEfforts`. Validation here therefore checks
   * what the schema actually constrains and does not invent a fixed list.
   */
  readonly effort?: string
}

/**
 * Reject a routing override the wire schema cannot carry, before any process.
 * @param routing - the caller-supplied per-run overrides.
 * @throws when a supplied field is present but not a non-empty string.
 */
function assertRouting(routing: CodexRouting): void {
  const fields = [['model', routing.model], ['effort', routing.effort]] as const
  for (const [field, value] of fields) {
    if (value === undefined) continue
    if (value.trim().length === 0) {
      throw new Error(`subagent-codex: routed ${field} must be a non-empty value`)
    }
  }
}

type CodexFailureStage =
  | 'initialize'
  | 'thread-start'
  | CodexWireFailureFacts['stage']
  | 'process'
  | 'teardown'

interface CodexFailureFacts {
  readonly stage: CodexFailureStage
  readonly category: string
  readonly httpStatus?: number | undefined
  readonly outcome?: SubprocessOutcome | undefined
}

function failureDiagnostic(facts: CodexFailureFacts): string {
  const fields = [
    'product: Codex',
    `stage: ${facts.stage}`,
    `category: ${facts.category}`,
  ]
  if (facts.httpStatus !== undefined) {
    fields.push(`HTTP status: ${facts.httpStatus}`)
  }
  const processFields = [
    ['exit code', facts.outcome?.exitCode],
    ['signal', facts.outcome?.signal],
  ] as const
  for (const [label, value] of processFields) {
    if (value !== null && value !== undefined) fields.push(`${label}: ${value}`)
  }
  return `Product subagent failure (${fields.join('; ')})`
}

/** The product facts recovered from a diagnostic string. */
export interface CodexDiagnosticFacts {
  /** The lifecycle stage the run failed in. */
  readonly stage: string
  /** The app-server error-info variant, or a stage-level category. */
  readonly category: string
  /** The upstream HTTP status, when the failure carried one. */
  readonly httpStatus?: number
}

/**
 * Recover the structured facts from a diagnostic this module produced.
 *
 * `SubagentResult.diagnostic` is a string, so a consumer that needs to branch
 * on the error-info variant — to tell a quota exhaustion apart from a rejected
 * request, say — would otherwise have to pattern-match prose it does not own.
 * Keeping the reader beside {@link failureDiagnostic} gives the format exactly
 * one owner, so the two cannot drift apart unnoticed.
 * @param diagnostic - a `SubagentResult.diagnostic` from this provider.
 * @returns the recovered facts, or `undefined` when the text is not one of ours.
 */
export function parseCodexDiagnostic(diagnostic: string): CodexDiagnosticFacts | undefined {
  const match = /^(?:subagent-codex: )?Product subagent failure \((.*)\)$/.exec(diagnostic)
  if (match === null) return undefined
  const fields = new Map<string, string>()
  for (const field of (match[1] ?? '').split('; ')) {
    const separator = field.indexOf(': ')
    if (separator > 0) fields.set(field.slice(0, separator), field.slice(separator + 2))
  }
  const stage = fields.get('stage')
  const category = fields.get('category')
  if (stage === undefined || category === undefined) return undefined
  const status = fields.get('HTTP status')
  const httpStatus = status === undefined ? undefined : Number.parseInt(status, 10)
  return {
    stage,
    category,
    ...httpStatus === undefined || Number.isNaN(httpStatus) ? {} : { httpStatus },
  }
}

class CodexRunFailure extends Error {
  constructor(
    readonly facts: CodexFailureFacts,
    cause?: unknown,
  ) {
    super(
      `subagent-codex: ${failureDiagnostic(facts)}`,
      cause === undefined ? undefined : { cause },
    )
    this.name = 'CodexRunFailure'
  }
}

/**
 * Hide an unpublished Host failure behind fixed safe startup facts.
 * @param cause Original Host failure retained for internal diagnostics.
 * @returns A startup failure whose message contains only fixed safe facts.
 */
export function codexStartupFailure(cause: unknown): Error {
  return new CodexRunFailure({
    stage: 'initialize',
    category: 'unknown',
  }, cause)
}

/**
 * Fixed package-local app-server command, independent of the host `PATH`.
 * @returns Node, the official wrapper, and the fixed app-server arguments.
 */
export function codexAppServerArgv(): string[] {
  return [process.execPath, CODEX_PACKAGE_BIN, 'app-server', '--stdio']
}

/** Fully resolved inputs for one Codex app-server run. */
export interface CodexRunSpec {
  /** Parent Session workspace, also supplied to `thread/start`. */
  readonly cwd: string
  /** Profile-selected native non-interactive permission mode. */
  readonly permissionMode: CodexPermissionMode
  /** Explicit deployment/test environment layered after the shared scrub. */
  readonly env: Record<string, string>
  /** Subprocess termination grace passed to the shared process-tree owner. */
  readonly disposeGraceMs: number
  /** Shared subprocess service spawn operation. */
  readonly spawn: (spec: SubprocessSpawnSpec) => SubprocessHandle
  /** Diagnostic sink for a post-publication error flattened into a result. */
  readonly onError?: (error: Error, stopReason: SubagentStopReason) => void
}

/** A `CodexRunSpec` that may also route this one run's model and effort. */
export interface CodexTaskSpec extends CodexRunSpec {
  /** Optional schema-verified per-run overrides; absent leaves defaults alone. */
  readonly routing?: CodexRouting
}

/**
 * The plain one-shot task, independent of the shared subagent request shape.
 *
 * `startCodexRun` needs a `SubagentStartRequest` because it is the shared
 * subagent service's extension point. A routed worker has no delegating parent
 * Session to build one from, so the transport below takes only what it
 * actually uses.
 */
export interface CodexTaskRequest {
  /** Validated non-empty text blocks forming the task. */
  readonly texts: readonly string[]
  /** Caller cancellation covering startup and the turn. */
  readonly signal: AbortSignal
}

function thrown(value: unknown): Error {
  /* v8 ignore next -- typed subprocess/wire failures reject with Error. */
  return value instanceof Error ? value : new Error(String(value))
}

/**
 * Validate and preserve the one-shot task before crossing the process boundary.
 * @param prompt - task content accepted from the shared subagent service.
 * @returns the exact non-empty text block sequence.
 */
export function textTask(prompt: readonly ContentBlock[]): string[] {
  if (prompt.length === 0) {
    throw new Error('subagent-codex: the one-shot task must contain only text blocks')
  }
  const texts: string[] = []
  for (const block of prompt) {
    if (block.type !== 'text') {
      throw new Error('subagent-codex: the one-shot task must contain only text blocks')
    }
    texts.push(block.text)
  }
  if (texts.every(text => text.trim().length === 0)) {
    throw new Error('subagent-codex: the one-shot task must not be empty')
  }
  return texts
}

/**
 * Close the private wire, terminate the managed process tree, and wait for the
 * subprocess owner to prove it is gone.
 * @param wire - private app-server protocol connection.
 * @param child - shared-service handle that owns the process tree.
 */
export async function disposeCodexChild(
  wire: CodexAppServerWire,
  child: SubprocessHandle,
): Promise<void> {
  wire.close()

  if (child.pid > 0) {
    let outcome: SubprocessOutcome | undefined
    void child.done.then(
      (value) => { outcome = value },
      /* v8 ignore next -- a positive pid excludes spawn-level done rejection. */
      () => {},
    )
    try {
      child.stdin?.end()
    } catch {
      // A concurrently closed stdin does not change tree ownership below.
    }
    child.terminate()
    try {
      await child.waitForExit()
    } catch (error: unknown) {
      throw new CodexRunFailure({
        stage: 'teardown',
        category: 'unknown',
        outcome,
      }, thrown(error))
    }
    await child.done
  } else {
    await child.done.catch(() => {})
  }
}

/**
 * Start the real `codex app-server --stdio` child and publish its one-shot run.
 *
 * This is the shared subagent service's entry point and is unchanged in
 * behaviour: it routes nothing, so the frames it emits are exactly those it
 * emitted before {@link startCodexTask} existed.
 * @param request - resolved shared subagent request.
 * @param spec - Workspace, environment, process service, and diagnostic policy.
 * @returns the published run after initialization and ephemeral thread creation.
 */
export async function startCodexRun(
  request: SubagentStartRequest,
  spec: CodexRunSpec,
): Promise<SubagentRun> {
  return startCodexTask({ texts: textTask(request.prompt), signal: request.signal }, spec)
}

/**
 * Start one Codex app-server child for a plain task, optionally routed.
 * @param request - the task text and the caller's cancellation signal.
 * @param spec - Workspace, environment, process service, diagnostics, routing.
 * @returns the published run after initialization and ephemeral thread creation.
 */
export async function startCodexTask(
  request: CodexTaskRequest,
  spec: CodexTaskSpec,
): Promise<SubagentRun> {
  const routing = spec.routing ?? {}
  // Reject an unusable override before spawning anything: a route the wire
  // cannot carry should cost no process and reach no frame.
  assertRouting(routing)
  const texts = request.texts
  if (request.signal.aborted) {
    throw new Error('subagent-codex: request was aborted before app-server startup')
  }

  let child: SubprocessHandle
  try {
    child = spec.spawn({
      argv: codexAppServerArgv(),
      cwd: spec.cwd,
      stdio: { stdin: 'pipe', stdout: 'pipe', stderr: 'pipe' },
      graceMs: spec.disposeGraceMs,
      env: spec.env,
    })
  } catch (error: unknown) {
    throw new CodexRunFailure({
      stage: 'initialize',
      category: 'unknown',
    }, thrown(error))
  }

  const wire = new CodexAppServerWire(
    child.stdout as NonNullable<SubprocessHandle['stdout']>,
    child.stdin as NonNullable<SubprocessHandle['stdin']>,
    spec.permissionMode,
    routing,
  )
  const onStderr = (chunk: Buffer | string): void => {
    const bytes = typeof chunk === 'string' ? Buffer.from(chunk) : chunk
    wire.observeStderr(bytes.toString())
    try {
      // Synchronous fd forwarding preserves byte order without owning a
      // backpressure queue. A slow host sink can block this event-loop turn.
      writeFileSync(process.stderr.fd, bytes)
    } catch {
      // Host stderr is an observation sink, not a child-run failure authority.
    }
  }
  const onStderrError = (): void => {
    // Stderr observation is auxiliary. JSON-RPC and child.done remain the
    // only terminal authorities if the diagnostic stream itself fails.
  }
  child.stderr?.on('data', onStderr)
  child.stderr?.on('error', onStderrError)
  const disposeProcess = async (): Promise<void> => {
    try {
      await disposeCodexChild(wire, child)
      // Let stderr already queued by the process close reach both bounded
      // diagnostic consumers before their listeners are detached.
      await new Promise<void>((resolve) => { setImmediate(resolve) })
    } finally {
      child.stderr?.off('data', onStderr)
      child.stderr?.off('error', onStderrError)
    }
  }

  let processFailureFacts: CodexFailureFacts | undefined
  const processFailure: Promise<never> = child.done.then<never>(
    (outcome) => {
      processFailureFacts = {
        stage: 'process',
        category: 'process-exit',
        outcome,
      }
      throw new CodexRunFailure(processFailureFacts)
    },
    (error: unknown) => {
      processFailureFacts = {
        stage: 'process',
        category: 'unknown',
      }
      throw new CodexRunFailure(processFailureFacts, thrown(error))
    },
  )
  // A normal post-result dispose also closes the process. Keep its expected
  // late rejection observed when the terminal result settles first.
  processFailure.catch(() => {})

  const runAbort = new AbortController()
  const requestCancel = (): void => {
    if (runAbort.signal.aborted) return
    runAbort.abort(new Error('subagent-codex: run cancelled locally'))
    wire.interrupt()
  }
  const onAbort = (): void => { requestCancel() }
  request.signal.addEventListener('abort', onAbort, { once: true })

  let startupStage: 'initialize' | 'thread-start' = 'initialize'
  try {
    wire.start()
    await Promise.race([wire.initialize(request.signal), processFailure])
    startupStage = 'thread-start'
    await Promise.race([wire.startThread(spec.cwd, request.signal), processFailure])
  } catch (error: unknown) {
    request.signal.removeEventListener('abort', onAbort)
    const cancelledBeforeCleanup = runAbort.signal.aborted
    if (!(error instanceof CodexRunFailure) && !cancelledBeforeCleanup) {
      // Node reports stdout EOF before the child close that owns its outcome.
      // Let an already-exiting process publish those facts before rollback.
      await new Promise<void>((resolve) => { setImmediate(resolve) })
    }
    const failure = new CodexRunFailure({
      stage: startupStage,
      category: 'unknown',
      outcome: error instanceof CodexRunFailure
        ? error.facts.outcome
        : processFailureFacts?.outcome,
    }, thrown(error))
    try {
      await disposeProcess()
    } catch (disposeError: unknown) {
      const cleanupFailure = thrown(disposeError)
      throw new AggregateError(
        [failure, cleanupFailure],
        `${failure.message}; ${cleanupFailure.message}`,
      )
    }
    if (cancelledBeforeCleanup) {
      throw new Error('subagent-codex: request was aborted before run publication')
    }
    try {
      request.signal.throwIfAborted()
    } catch {
      throw new Error('subagent-codex: request was aborted before run publication')
    }
    throw failure
  }

  const collectOutput = (): ContentBlock[] => wire.collectOutput()
  let diagnostic: string | undefined
  const recordFailureDiagnostic = (facts: CodexFailureFacts): string => {
    const failure = failureDiagnostic(facts)
    const permission = wire.collectDiagnostic()
    diagnostic = permission === undefined
      ? failure
      : `${failure}\n${permission}`
    return diagnostic
  }
  const withProcessOutcome = (facts: CodexFailureFacts): CodexFailureFacts => {
    const outcome = processFailureFacts?.outcome
    return outcome === undefined
      ? facts
      : { ...facts, outcome }
  }
  const publishedProcessFailure = processFailure.catch(
    async (error: unknown): Promise<never> => {
      // Frames already queued by the exiting app-server remain authoritative.
      // One I/O turn lets them settle before process exit ends the run.
      await new Promise<void>((resolve) => { setImmediate(resolve) })
      throw error
    },
  )
  const result: Promise<SubagentResult> = settleRunResult({
    attempt: async () => {
      try {
        const terminal = await Promise.race([
          wire.runTurn(texts, runAbort.signal),
          publishedProcessFailure,
        ])
        if (terminal.stopReason === 'completed') return terminal
        // Let stderr already queued with the terminal frame contribute its
        // fixed permission fact before the non-completed result is snapshotted.
        await new Promise<void>((resolve) => { setImmediate(resolve) })
        const facts = withProcessOutcome(wire.collectFailure())
        return { ...terminal, diagnostic: recordFailureDiagnostic(facts) }
      } catch (error: unknown) {
        // Give stderr data already queued in Node one turn to reach the wire
        // before settlement snapshots the diagnostic.
        await new Promise<void>((resolve) => { setImmediate(resolve) })
        const endedBeforeTerminal = wire.endedBeforeTerminal()
        if (
          endedBeforeTerminal
          && processFailureFacts === undefined
          && !runAbort.signal.aborted
        ) {
          try {
            const exited = await child.waitForExit(
              AbortSignal.timeout(Math.ceil(spec.disposeGraceMs)),
            )
            if (exited) await child.done
          } catch {
            // The wire failure remains authoritative when exit observation fails.
          }
        }
        const facts = error instanceof CodexRunFailure
          ? error.facts
          : endedBeforeTerminal && processFailureFacts !== undefined
            ? processFailureFacts
            : withProcessOutcome(wire.collectFailure())
        recordFailureDiagnostic(facts)
        throw error instanceof CodexRunFailure
          ? error
          : new CodexRunFailure(facts, thrown(error))
      }
    },
    collectOutput,
    collectDiagnostic: () => diagnostic,
    cancelled: () => runAbort.signal.aborted,
    onError: spec.onError,
    signal: request.signal,
    onAbort,
  })

  return subprocessRunHandle({
    id: SessionId(randomUUID()),
    result,
    signal: request.signal,
    onAbort,
    requestCancel,
    teardown: disposeProcess,
  })
}
